sudo: false
language: php
php:
  - 7.1
services:
  - mysql

before_script:
  - phpenv config-rm xdebug.ini # Disable x-debug to speed up things
  # Get the token from github and put it in travis repo under GITHUB_COMPOSER_AUTH ENV variable, then uncomment line below.
  #  - composer config -g github-oauth.github.com $GITHUB_COMPOSER_AUTH
  - SYMFONY_ENV=test composer install --no-interaction --prefer-dist

  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
  - wget -c -nc --retry-connrefused --tries=0 http://goo.gl/EoH85x -O selenium-server-standalone.jar
  - nohup bash -c "java -jar selenium-server-standalone.jar &" && sleep 1; cat nohup.out

  # Prepare database
  - bin/console doctrine:database:create -e test
  - bin/console doctrine:schema:create -e test
  - bin/console doctrine:fixtures:load -n -e test

  - nohup bash -c "bin/console server:start localhost:8000 -e test" && sleep 1; cat nohup.out

script:
  - vendor/bin/phpcs -p --standard=PSR2 --extensions=php ./src --ignore=*/DataFixtures/*
  - vendor/bin/phpunit
  - vendor/bin/codecept run

notifications:
  slack: nfqakademija:D39BmJYjiYZsrNylRdNfIBzm
