<?php

namespace AppBundle\Repository;

/**
 * JobApplyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobApplyRepository extends \Doctrine\ORM\EntityRepository
{
}
