<?php

namespace AppBundle\Repository;

/**
 * JobAdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobAdRepository extends \Doctrine\ORM\EntityRepository
{
}
